### ISSUE TITLE
arithmetic on a nil value in 'xpcall'

### ISSUE THREAD

**Issue by bartkoevoets** [emptyrivers/BrewmasterTools#22] opened 2018-07-20 23:09 UTC
* Explain what you were doing when the error occured:
Just having it loaded

* Do you have an error log? If so, put it here:
1760x [string "--[[ Error in ' Normalized Stagger' ]]retur..."]:4: attempt to perform arithmetic on a nil value
[C]: in function `xpcall'
WeakAuras\RegionTypes\AuraBar.lua:1292: in function `UpdateCustomText'
WeakAuras\WeakAuras-2.6.0.lua:3544: in function <WeakAuras\WeakAuras.lua:3538>

Locals:
nil

* What version of BrewmasterTools are you using?
v0.3.0

* When was the last version which did not have this issue?
whatever the version before this one was

**Comment by emptyrivers** [comment] 2018-07-21 08:44
Duplicate of #20

**Closed as completed by emptyrivers** 2018-07-21 08:44 UTC
