### ISSUE TITLE
Norm stagger WA not working with addon or in general for myself.

### ISSUE THREAD

**Issue by Cpdpro** [emptyrivers/BrewmasterTools#3] opened 2017-06-24 06:51 UTC
The WA isn't working for me at all and i just keep getting this error spammed in my chat. 
[02:45:43] [string "function(progress, r1, g1, b1, a1, r2, g2, b2, a2)..."]:1: '<name>' expected near '('
[02:45:43] [string "function(progress, r1, g1, b1, a1, r2, g2, b2, a2)..."]:1: '<name>' expected near '('
[02:45:48] [string "function(progress, r1, g1, b1, a1, r2, g2, b2, a2)..."]:1: '<name>' expected near '('

**Comment by emptyrivers** [comment] 2017-06-24 06:52
Duplicate of #1. Update WeakAuras, log out, and log back in.

**Closed as completed by emptyrivers** 2017-06-24 06:52 UTC
